
USE [master]
GO

/****** Object:  Database [SemenCommanderDB]    Script Date: 04.01.2023 1:39:15 ******/
CREATE DATABASE [SemenCommanderDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SemenCommanderDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SemenCommanderDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SemenCommanderDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SemenCommanderDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

ALTER DATABASE [SemenCommanderDB] SET COMPATIBILITY_LEVEL = 160
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SemenCommanderDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SemenCommanderDB] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [SemenCommanderDB] SET ANSI_NULLS OFF
GO

ALTER DATABASE [SemenCommanderDB] SET ANSI_PADDING OFF
GO

ALTER DATABASE [SemenCommanderDB] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [SemenCommanderDB] SET ARITHABORT OFF
GO

ALTER DATABASE [SemenCommanderDB] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [SemenCommanderDB] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [SemenCommanderDB] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [SemenCommanderDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [SemenCommanderDB] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [SemenCommanderDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [SemenCommanderDB] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [SemenCommanderDB] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [SemenCommanderDB] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [SemenCommanderDB] SET  DISABLE_BROKER
GO

ALTER DATABASE [SemenCommanderDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [SemenCommanderDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [SemenCommanderDB] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [SemenCommanderDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [SemenCommanderDB] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [SemenCommanderDB] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [SemenCommanderDB] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [SemenCommanderDB] SET RECOVERY SIMPLE
GO

ALTER DATABASE [SemenCommanderDB] SET  MULTI_USER
GO

ALTER DATABASE [SemenCommanderDB] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [SemenCommanderDB] SET DB_CHAINING OFF
GO

ALTER DATABASE [SemenCommanderDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [SemenCommanderDB] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [SemenCommanderDB] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [SemenCommanderDB] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [SemenCommanderDB] SET QUERY_STORE = ON
GO

USE [SemenCommanderDB]
GO

/****** Object:  Table [dbo].[Files]    Script Date: 04.01.2023 1:39:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Users]    Script Date: 04.01.2023 1:39:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [SemenCommanderDB] SET  READ_WRITE
GO

ALTER DATABASE [SemenCommanderDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)

GO

--Syntax Error: Incorrect syntax near WAIT_STATS_CAPTURE_MODE.
--ALTER DATABASE [SemenCommanderDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)



GO
